### PR TITLE
Brill: Update for site changes

### LINKED ISSUE #3317: Brill: Bibliography detection broken, some books translated as bookSections without authors
See tests

### PR DESCRIPTION
**Pull request by AbeJellinek**
Fixes #3317. Needs #3318. Should consider merging the `citation_inbook_title` fix (used in two translators now) into EM itself.

### CODE REVIEW

File: Brill.js [hunk 1]
```diff
@@ -107,15 +110,38 @@ function scrape(doc, url) {
...
+		if (item.itemType == 'encyclopediaArticle' && !item.encyclopediaTitle) {
+			item.encyclopediaTitle = text(doc, '.source-link a');
+		}
 		
 		if (item.abstractNote && item.abstractNote.endsWith('by Brill.')) {
 			delete item.abstractNote;
 		}
+
+		if (!item.publisher) {
+			item.published = 'Brill';
```
Comment (dstillman) [inline Brill.js:123]: `publisher` — is this not covered by any tests?
